Fixing the error with the kv name

diff --git a/.github/workflows/key-vault.yml b/.github/workflows/key-vault.yml
--- a/.github/workflows/key-vault.yml
+++ b/.github/workflows/key-vault.yml
@@ -95,11 +95,15 @@ jobs:
         working-directory: environments/DEV
       
       - name: List DEV folder contents
-        run: ls -la
+        run: ls -la | ls -b environments/DEV
+        working-directory: environments/DEV
+
+      - name: Assert dev.tfvars exists
+        run: test -f dev.tfvars || (echo "dev.tfvars missing!" && exit 1)
         working-directory: environments/DEV
 
       - name: Terraform Plan
-        run: terraform plan -var-file="dev.tfvars" -out=tfplan
+        run: terraform plan -var-file="${GITHUB_WORKSPACE}/environments/DEV/dev.tfvars" -out=tfplan
         working-directory: environments/DEV
 
       - name: Terraform Apply
